#
# Copyright (c) 2016 Carleton Stuberg - http://imcpwn.com
# BrowserBackdoorServer by IMcPwn.
# See the file 'LICENSE' for copying permission
#

host: "0.0.0.0"
port: 1234
# Requires valid private key and certificate.
secure: false
priv_key: "privkey.pem"
cert_chain: "cert.pem"
